# Generated by Django 3.0.5 on 2020-08-07 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
