# Generated by Django 3.0.5 on 2020-08-07 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
