# Generated by Django 3.0.5 on 2020-08-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='files')),
                ('comment_by_secretary', models.TextField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
