# Generated by Django 3.0.5 on 2020-08-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200809_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='comment_by_secretary',
            new_name='comment_from_secretary',
        ),
        migrations.AddField(
            model_name='file',
            name='comment_from_perm_sec1',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='comment_from_perm_sec2',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='comment_from_ssg',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='date_of_file',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='moved_by_perm_sec1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='moved_by_perm_sec2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='moved_to_ssg',
            field=models.BooleanField(default=False),
        ),
    ]
