# Generated by Django 3.0.5 on 2020-08-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200809_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_of_file',
        ),
    ]
