# Generated by Django 3.0.5 on 2020-08-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_file_date_of_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
