# Generated by Django 3.0.5 on 2020-08-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200810_0446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='moved_to_ssg',
            new_name='moved_by_ssg',
        ),
    ]
